services:
  # Railsのコンテナ
  backend:
    # イメージはDockerfileを使う
    build:
      # Dockerfileのあるディレクトリを指定する
      context: ./backend

    # コンテナ起動時に実行するコマンド
    command: bash -c "tail -f log/development.log"

    # ローカルのファイルとコンテナのファイルを共有する
    volumes:
      - ./backend:/myapp

    # Railsのポート番号
    ports:
      - 3001:3000

    # PostgreSQLのコンテナが起動してからRailsのコンテナを起動する
    depends_on:
      - db

    # 標準入出力を扱う
    tty: true

    # 標準入力を扱う
    stdin_open: true

  # PostgreSQLのコンテナ
  db:
    # PostgreSQLのイメージを使う
    image: postgres:16

    # 環境変数
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'

    # ポート番号
    ports:
      - '5432:5432'

    # データベースのデータを永続的に保存する
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/myapp
    ports:
      - '3000:3000'

# データベースのデータを永続的に保存する
volumes:
  postgres_data:
