import { Company } from "@/types/Company";

export const companyList: Company[] = [
  {
    id: 1,
    name: "Sky株式会社",
    selectionType: "本選考",
    selectionStatus: "最終面接",
    selectionDate: "2025-02-01 14:00",
    selectionResult: "内定",
  },
  {
    id: 2,
    name: "株式会社ラクス",
    selectionType: "早期選考",
    selectionStatus: "１次面接",
    selectionDate: "2025-02-01 11:00",
    selectionResult: "合格",
  },
  {
    id: 3,
    name: "LINEヤフー株式会社",
    selectionType: "インターン",
    selectionStatus: "面談",
    selectionDate: "2025-03-21 16:00",
    selectionResult: "不合格",
  },
  {
    id: 4,
    name: "CTC",
    selectionType: "本選考",
    selectionStatus: "２次面接",
    selectionDate: "2025-02-01 14:00",
    selectionResult: "辞退",
  },
  {
    id: 5,
    name: "リクルートホールディングス",
    selectionType: "インターン",
    selectionStatus: "最終面接",
    selectionDate: "2025-02-01 14:00",
    selectionResult: "内定",
  },
  {
    id: 6,
    name: "Sky株式会社",
    selectionType: "本選考",
    selectionStatus: "最終面接",
    selectionDate: "2025-02-01 14:00",
    selectionResult: "内定",
  },
  {
    id: 7,
    name: "株式会社ラクス",
    selectionType: "早期選考",
    selectionStatus: "１次面接",
    selectionDate: "2025-02-01 11:00",
    selectionResult: "合格",
  },
  {
    id: 8,
    name: "LINEヤフー株式会社",
    selectionType: "インターン",
    selectionStatus: "面談",
    selectionDate: "2025-03-21 16:00",
    selectionResult: "不合格",
  },
  {
    id: 9,
    name: "CTC",
    selectionType: "本選考",
    selectionStatus: "２次面接",
    selectionDate: "2025-02-01 14:00",
    selectionResult: "辞退",
  },
  {
    id: 10,
    name: "リクルートホールディングス",
    selectionType: "インターン",
    selectionStatus: "最終面接",
    selectionDate: "2025-02-01 14:00",
    selectionResult: "内定",
  },
];
